import { FPS, type Timeline } from "./schema";

/**
 * A timeline used only by the Remotion studio, so `npm run video:studio` opens
 * on something real instead of a black frame. It exercises every overlay type
 * and every effect, which makes it the fastest way to eyeball a renderer change.
 */
export const DEMO_TIMELINE: Timeline = {
  id: "demo",
  formatId: "FORMAT_21",
  fps: FPS,
  width: 1080,
  height: 1920,
  durationMs: 16000,
  background: "#000000",
  beatGridMs: [0, 1935, 3870, 5806, 7741, 9677, 11612, 13548, 15483],
  editNotes:
    "Démo du moteur de rendu : réaction + bandeau figé, coupe sur la démo, punch-in sur le chiffre, retour visage.",
  video: [
    {
      id: "v0",
      src: "#14304a",
      kind: "color",
      startMs: 0,
      durationMs: 3200,
      sourceInMs: 0,
      layer: 0,
      layout: { mode: "full" },
      fit: "cover",
      opacity: 1,
      effects: [
        { type: "kenBurns", fromScale: 1.18, toScale: 1.02, fromX: 0, toX: 0, fromY: 0, toY: 0, easing: "easeOut" },
        { type: "shake", amplitudePx: 3, frequencyHz: 1.6 },
      ],
      transitionIn: { type: "cut", durationMs: 0, direction: "left" },
      note: "Réaction + bandeau",
    },
    {
      id: "v1",
      src: "#0d1b2a",
      kind: "color",
      startMs: 3200,
      durationMs: 7800,
      sourceInMs: 0,
      layer: 0,
      layout: { mode: "full" },
      fit: "cover",
      opacity: 1,
      effects: [
        { type: "kenBurns", fromScale: 1.0, toScale: 1.06, fromX: 0, toX: 0, fromY: 0, toY: -20, easing: "linear" },
        { type: "punchIn", atMs: 4200, scale: 1.2, attackMs: 110, holdMs: 460, releaseMs: 200 },
      ],
      transitionIn: { type: "whipPan", durationMs: 160, direction: "left" },
      note: "Démo produit",
    },
    {
      id: "v2",
      src: "#1b2a3a",
      kind: "color",
      startMs: 11000,
      durationMs: 5000,
      sourceInMs: 0,
      layer: 0,
      layout: { mode: "full" },
      fit: "cover",
      opacity: 1,
      effects: [
        { type: "kenBurns", fromScale: 1.05, toScale: 1.12, fromX: 0, toX: 14, fromY: 0, toY: -8, easing: "linear" },
      ],
      transitionIn: { type: "cut", durationMs: 0, direction: "left" },
      note: "Retour visage — la chute",
    },
  ],
  overlays: [
    {
      type: "textBar",
      id: "hook",
      text: "Tu fais encore ça à la main ?",
      startMs: 0,
      durationMs: 3200,
      anchor: { y: 450, align: "center" },
      enter: "pop",
      style: {
        background: "#FE2C55",
        color: "#FFFFFF",
        fontSize: 58,
        fontWeight: 900,
        uppercase: true,
        radius: 14,
        paddingX: 28,
        paddingY: 16,
        maxWidth: 920,
        shadow: true,
      },
    },
    {
      type: "captions",
      id: "captions",
      anchor: { y: 980, align: "center" },
      wordsPerBlock: 3,
      style: {
        fontSize: 64,
        color: "#FFFFFF",
        highlight: "#FFE600",
        strokeWidth: 12,
        strokeColor: "#000000",
        uppercase: true,
      },
      words: [
        { word: "Tu", startMs: 3400, endMs: 3620, emphasis: false },
        { word: "ouvres,", startMs: 3620, endMs: 4100, emphasis: false },
        { word: "tu", startMs: 4100, endMs: 4260, emphasis: false },
        { word: "colles", startMs: 4260, endMs: 4720, emphasis: true },
        { word: "ça", startMs: 4720, endMs: 4900, emphasis: false },
        { word: "ici,", startMs: 4900, endMs: 5300, emphasis: false },
        { word: "tu", startMs: 5500, endMs: 5660, emphasis: false },
        { word: "cliques…", startMs: 5660, endMs: 6300, emphasis: true },
        { word: "et", startMs: 6600, endMs: 6760, emphasis: false },
        { word: "regarde", startMs: 6760, endMs: 7300, emphasis: true },
        { word: "le", startMs: 7300, endMs: 7440, emphasis: false },
        { word: "résultat.", startMs: 7440, endMs: 8100, emphasis: true },
        { word: "12", startMs: 8400, endMs: 8700, emphasis: true },
        { word: "secondes.", startMs: 8700, endMs: 9400, emphasis: true },
      ],
    },
    {
      type: "annotation",
      id: "ann1",
      shape: "circle",
      x: 540,
      y: 1250,
      width: 300,
      height: 170,
      rotation: -4,
      color: "#FE2C55",
      startMs: 5600,
      durationMs: 1200,
      label: "un seul bouton",
    },
    {
      type: "timer",
      id: "chrono",
      mode: "countdown",
      fromMs: 12000,
      startMs: 3200,
      durationMs: 7800,
      anchor: { y: 300, align: "right" },
      urgentBelowMs: 4000,
      freezeAtEnd: true,
    },
    {
      type: "stepBadge",
      id: "step1",
      index: 1,
      label: "Importer",
      startMs: 3600,
      durationMs: 2000,
      checkAtMs: 5000,
      anchor: { y: 1330, align: "left" },
    },
    {
      type: "storyCard",
      id: "card2",
      text: "12 secondes au lieu de 3 heures.",
      startMs: 11400,
      durationMs: 3200,
      anchor: { y: 620, align: "center" },
      enter: "fadeSlide",
      style: {
        fontSize: 54,
        color: "#FFFFFF",
        shadow: true,
        background: "transparent",
        maxWidth: 880,
        align: "center",
      },
    },
  ],
  audio: [],
};
